name: CI-CD Wisecow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.abhiverma9889 }}
        password: ${{ secrets.Rits9889@ }}

    # 3️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.abhiverma9889 }}/wisecow:latest .

    # 4️⃣ Push Docker image
    - name: Push Docker image
      run: docker push ${{ secrets.abhiverma9889 }}/wisecow:latest

    # 5️⃣ Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # 6️⃣ Deploy to Kubernetes
    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        IMAGE: ${{ secrets.DOCKER_USER }}/wisecow:latest
      run: |
        # Update image in deployment
        kubectl set image -f k8s/deployment.yaml wisecow=$IMAGE --record

        # Apply all manifests
        kubectl apply -f k8s/
